import type { ReadingMessage } from '@shared/types'

/**
 * Pure parsing for the Reading view: walk a transcript's JSONL lines into an
 * ordered list of rendered messages (user/assistant text + compact tool rows).
 * No I/O so it's unit-testable. Mirrors the content-block walk in agentParse.ts
 * and reuses the harness-noise rules from sessionHistoryParse.ts.
 */

interface RawContent {
  type?: string
  id?: string
  name?: string
  input?: unknown
  tool_use_id?: string
  is_error?: boolean
  text?: unknown
}
interface RawLine {
  type?: string
  uuid?: string
  isSidechain?: boolean
  isMeta?: boolean
  isCompactSummary?: boolean
  isVisibleInTranscriptOnly?: boolean
  timestamp?: string
  message?: { content?: string | RawContent[] }
}

const str = (x: unknown): string => (typeof x === 'string' ? x : '')

// Harness-injected blocks that arrive as messages but never appear in Claude's
// rendered conversation (kept in sync with sessionHistoryParse.ts).
const NOISE_TAG =
  /^<(task-notification|command-name|command-message|command-args|local-command-stdout|local-command-stderr|system-reminder|bash-input|bash-stdout|bash-stderr|user-prompt-submit-hook|user-memory-input)\b/i
const NOISE_CAVEAT = /^Caveat: The messages below were generated by the user/i
const isNoise = (t: string): boolean => {
  const s = t.trimStart()
  return NOISE_TAG.test(s) || NOISE_CAVEAT.test(s)
}

const BASENAME = (p: string): string => p.split(/[\\/]/).filter(Boolean).pop() ?? p

/** A compact, human label for a tool action. */
export function toolSummary(name: string, input: unknown): string {
  const o = (input ?? {}) as Record<string, unknown>
  if (name === 'Edit' || name === 'Write' || name === 'Read' || name === 'NotebookEdit') {
    const fp = str(o.file_path)
    if (fp) return BASENAME(fp)
  }
  if (name === 'Bash') {
    const cmd = str(o.command).replace(/\s+/g, ' ').trim()
    if (cmd) return cmd.length > 80 ? cmd.slice(0, 79) + '…' : cmd
  }
  if (name === 'Agent' || name === 'Task') {
    const d = str(o.description)
    if (d) return d
  }
  return name
}

/** Extract the joined, noise-filtered text of a content value. */
function textOf(content: string | RawContent[] | undefined): string {
  if (typeof content === 'string') return isNoise(content) ? '' : content
  if (!Array.isArray(content)) return ''
  return content
    .filter((b) => b && b.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text as string)
    .filter((t) => !isNoise(t))
    .join('\n')
}

/**
 * Everything a conversation parse must remember BETWEEN chunks. A transcript is
 * read incrementally (a full parse on first sight, then only appended bytes), and
 * a `tool_result` routinely lands in a later chunk than its `tool_use` — so this
 * state has to survive the chunk boundary or every tool row would stay stuck on
 * `ok: null`, dedup would miss at the seam, and synthesized ids would restart at
 * `m0` and collide with an earlier chunk's.
 */
export interface ConversationParseState {
  /** tool_use id → the message object it created (a REFERENCE, so trimming the
   * conversation array can't invalidate it). */
  pendingTools: Map<string, ReadingMessage>
  /** carried across chunks so compaction replays still dedup at a boundary. */
  lastUserText: string
  /** monotonic across chunks so synthesized ids never collide. */
  synth: number
}

export function newConversationParseState(): ConversationParseState {
  return { pendingTools: new Map(), lastUserText: '', synth: 0 }
}

/**
 * Parse `lines` and APPEND to `messages`, resolving tool results against tools
 * already present (possibly created by an earlier chunk).
 */
export function appendConversation(
  messages: ReadingMessage[],
  lines: string[],
  state: ConversationParseState
): void {
  for (const line of lines) {
    const s = line.trim()
    if (!s || s[0] !== '{') continue
    let o: RawLine
    try {
      o = JSON.parse(s) as RawLine
    } catch {
      continue
    }
    if (o.isSidechain || o.isMeta || o.isCompactSummary || o.isVisibleInTranscriptOnly) continue
    if (o.type !== 'user' && o.type !== 'assistant') continue

    const parsedTs = Date.parse(o.timestamp ?? '')
    const ts = Number.isFinite(parsedTs) ? parsedTs : 0
    const content = o.message?.content
    const baseId = str(o.uuid) || `m${state.synth++}`

    // tool_result blocks: pair to the tool row they complete (don't render as text).
    if (Array.isArray(content)) {
      for (const b of content) {
        if (b && b.type === 'tool_result' && typeof b.tool_use_id === 'string') {
          const msg = state.pendingTools.get(b.tool_use_id)
          if (msg?.tool) {
            msg.tool.ok = b.is_error ? false : true
            state.pendingTools.delete(b.tool_use_id)
          }
        }
      }
      // tool_use blocks → compact tool rows.
      for (const b of content) {
        if (b && b.type === 'tool_use' && typeof b.name === 'string') {
          const id = str(b.id) || `${baseId}-${b.name}`
          const msg: ReadingMessage = {
            id,
            role: 'tool',
            ts,
            tool: { name: b.name, summary: toolSummary(b.name, b.input), ok: null }
          }
          messages.push(msg)
          if (b.id) state.pendingTools.set(b.id, msg)
        }
      }
    }

    // user/assistant prose.
    const text = textOf(content).trim()
    if (!text) continue
    if (o.type === 'user') {
      if (text === state.lastUserText) continue // compaction replays the same prompt
      state.lastUserText = text
    } else {
      state.lastUserText = '' // an assistant turn ends the consecutive-user window
    }
    messages.push({ id: baseId, role: o.type === 'user' ? 'user' : 'assistant', ts, text })
  }
}

/** One-shot parse of a complete set of lines (fresh array + fresh state). */
export function parseConversation(lines: string[]): ReadingMessage[] {
  const out: ReadingMessage[] = []
  appendConversation(out, lines, newConversationParseState())
  return out
}

/**
 * Split freshly-appended transcript bytes into complete lines plus the number of
 * BYTES they occupied, leaving any trailing partial line for the next read (a
 * transcript is appended to while we read it). Pure + unit-testable.
 */
export function sliceCompleteLines(text: string): { lines: string[]; consumed: number } {
  const lastNl = text.lastIndexOf('\n')
  if (lastNl < 0) return { lines: [], consumed: 0 }
  const complete = text.slice(0, lastNl)
  return { lines: complete.split('\n'), consumed: Buffer.byteLength(complete, 'utf8') + 1 }
}

/** Split `lines` into consecutive runs of about `maxChars` characters (a run
 * closes once it reaches the limit), so a big transcript can be parsed a run at
 * a time with the event loop free in between. */
export function linesByChars(lines: string[], maxChars: number): string[][] {
  const runs: string[][] = []
  let run: string[] = []
  let size = 0
  for (const line of lines) {
    run.push(line)
    size += line.length
    if (size >= maxChars) {
      runs.push(run)
      run = []
      size = 0
    }
  }
  if (run.length) runs.push(run)
  return runs
}

/**
 * Parse a slice read from byte `start` of a transcript. A read that began
 * mid-file opens with a fragment of a record, which is dropped. Returns the
 * complete records plus the ABSOLUTE file offset where the parsed region ends —
 * the caller stores that as its resume point, so it must account for the dropped
 * fragment AND leave any unterminated trailing line unconsumed.
 */
export function parseTailSlice(text: string, start: number): { lines: string[]; end: number } {
  let body = text
  let dropped = 0
  if (start > 0) {
    const nl = body.indexOf('\n')
    if (nl >= 0) {
      dropped = Buffer.byteLength(body.slice(0, nl + 1), 'utf8')
      body = body.slice(nl + 1)
    }
  }
  const { lines, consumed } = sliceCompleteLines(body)
  return { lines, end: start + dropped + consumed }
}
