import type { ReadingMessage } from '@shared/types'

/**
 * Pure parsing for the Reading view: walk a transcript's JSONL lines into an
 * ordered list of rendered messages (user/assistant text + compact tool rows).
 * No I/O so it's unit-testable. Mirrors the content-block walk in agentParse.ts
 * and reuses the harness-noise rules from sessionHistoryParse.ts.
 */

interface RawContent {
  type?: string
  id?: string
  name?: string
  input?: unknown
  tool_use_id?: string
  is_error?: boolean
  text?: unknown
}
interface RawLine {
  type?: string
  uuid?: string
  isSidechain?: boolean
  isMeta?: boolean
  isCompactSummary?: boolean
  isVisibleInTranscriptOnly?: boolean
  timestamp?: string
  message?: { content?: string | RawContent[] }
}

const str = (x: unknown): string => (typeof x === 'string' ? x : '')

// Harness-injected blocks that arrive as messages but never appear in Claude's
// rendered conversation (kept in sync with sessionHistoryParse.ts).
const NOISE_TAG =
  /^<(task-notification|command-name|command-message|command-args|local-command-stdout|local-command-stderr|system-reminder|bash-input|bash-stdout|bash-stderr|user-prompt-submit-hook|user-memory-input)\b/i
const NOISE_CAVEAT = /^Caveat: The messages below were generated by the user/i
const isNoise = (t: string): boolean => {
  const s = t.trimStart()
  return NOISE_TAG.test(s) || NOISE_CAVEAT.test(s)
}

const BASENAME = (p: string): string => p.split(/[\\/]/).filter(Boolean).pop() ?? p

/** A compact, human label for a tool action. */
export function toolSummary(name: string, input: unknown): string {
  const o = (input ?? {}) as Record<string, unknown>
  if (name === 'Edit' || name === 'Write' || name === 'Read' || name === 'NotebookEdit') {
    const fp = str(o.file_path)
    if (fp) return BASENAME(fp)
  }
  if (name === 'Bash') {
    const cmd = str(o.command).replace(/\s+/g, ' ').trim()
    if (cmd) return cmd.length > 80 ? cmd.slice(0, 79) + '…' : cmd
  }
  if (name === 'Agent' || name === 'Task') {
    const d = str(o.description)
    if (d) return d
  }
  return name
}

/** Extract the joined, noise-filtered text of a content value. */
function textOf(content: string | RawContent[] | undefined): string {
  if (typeof content === 'string') return isNoise(content) ? '' : content
  if (!Array.isArray(content)) return ''
  return content
    .filter((b) => b && b.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text as string)
    .filter((t) => !isNoise(t))
    .join('\n')
}

export function parseConversation(lines: string[]): ReadingMessage[] {
  const out: ReadingMessage[] = []
  const toolIndexById = new Map<string, number>() // tool_use id → index in `out`
  let lastUserText = ''
  let synth = 0

  for (const line of lines) {
    const s = line.trim()
    if (!s || s[0] !== '{') continue
    let o: RawLine
    try {
      o = JSON.parse(s) as RawLine
    } catch {
      continue
    }
    if (o.isSidechain || o.isMeta || o.isCompactSummary || o.isVisibleInTranscriptOnly) continue
    if (o.type !== 'user' && o.type !== 'assistant') continue

    const parsedTs = Date.parse(o.timestamp ?? '')
    const ts = Number.isFinite(parsedTs) ? parsedTs : 0
    const content = o.message?.content
    const baseId = str(o.uuid) || `m${synth++}`

    // tool_result blocks: pair to the tool row they complete (don't render as text).
    if (Array.isArray(content)) {
      for (const b of content) {
        if (b && b.type === 'tool_result' && typeof b.tool_use_id === 'string') {
          const idx = toolIndexById.get(b.tool_use_id)
          if (idx != null && out[idx].tool) out[idx].tool!.ok = b.is_error ? false : true
        }
      }
      // tool_use blocks → compact tool rows.
      for (const b of content) {
        if (b && b.type === 'tool_use' && typeof b.name === 'string') {
          const id = str(b.id) || `${baseId}-${b.name}`
          out.push({ id, role: 'tool', ts, tool: { name: b.name, summary: toolSummary(b.name, b.input), ok: null } })
          if (b.id) toolIndexById.set(b.id, out.length - 1)
        }
      }
    }

    // user/assistant prose.
    const text = textOf(content).trim()
    if (!text) continue
    if (o.type === 'user') {
      if (text === lastUserText) continue // compaction replays the same prompt
      lastUserText = text
    } else {
      lastUserText = '' // an assistant turn ends the consecutive-user window
    }
    out.push({ id: baseId, role: o.type === 'user' ? 'user' : 'assistant', ts, text })
  }
  return out
}

/**
 * Split freshly-appended transcript bytes into complete lines plus the number of
 * BYTES they occupied, leaving any trailing partial line for the next read (a
 * transcript is appended to while we read it). Pure + unit-testable.
 */
export function sliceCompleteLines(text: string): { lines: string[]; consumed: number } {
  const lastNl = text.lastIndexOf('\n')
  if (lastNl < 0) return { lines: [], consumed: 0 }
  const complete = text.slice(0, lastNl)
  return { lines: complete.split('\n'), consumed: Buffer.byteLength(complete, 'utf8') + 1 }
}

/**
 * Parse a slice read from byte `start` of a transcript. A read that began
 * mid-file opens with a fragment of a record, which is dropped. Returns the
 * complete records plus the ABSOLUTE file offset where the parsed region ends —
 * the caller stores that as its resume point, so it must account for the dropped
 * fragment AND leave any unterminated trailing line unconsumed.
 */
export function parseTailSlice(text: string, start: number): { lines: string[]; end: number } {
  let body = text
  let dropped = 0
  if (start > 0) {
    const nl = body.indexOf('\n')
    if (nl >= 0) {
      dropped = Buffer.byteLength(body.slice(0, nl + 1), 'utf8')
      body = body.slice(nl + 1)
    }
  }
  const { lines, consumed } = sliceCompleteLines(body)
  return { lines, end: start + dropped + consumed }
}
