import type { SessionHistory } from '@shared/types'

/**
 * Pure parsing for the session-history (checkpoint) navigator: extract the user's
 * typed prompts from a transcript, read-only. One checkpoint = one user prompt
 * (matches Claude Code's own checkpoint model). No I/O so it's unit-testable.
 */

export interface PromptRec {
  sessionId: string
  cwd: string
  ts: number
  text: string
}

interface RawContent {
  type?: string
  text?: unknown
}
interface RawLine {
  type?: string
  isSidechain?: boolean
  isMeta?: boolean
  isCompactSummary?: boolean
  isVisibleInTranscriptOnly?: boolean
  sessionId?: string
  cwd?: string
  timestamp?: string
  message?: { content?: string | RawContent[] }
}

const str = (x: unknown): string => (typeof x === 'string' ? x : '')

/**
 * Harness/tooling messages that arrive as `type:"user"` but are NOT something the
 * user typed — slash-command expansions, background task-completion notices, hook
 * output, local-command stdout, system reminders, the bracketed-paste caveat. They
 * never appear in Claude's rendered conversation, so they're noise in the rail AND
 * unreachable by scroll. Recognized by their leading wrapper tag / sentinel. */
const NOISE_TAG =
  /^<(task-notification|command-name|command-message|command-args|local-command-stdout|local-command-stderr|system-reminder|bash-input|bash-stdout|bash-stderr|user-prompt-submit-hook|user-memory-input)\b/i
const NOISE_CAVEAT = /^Caveat: The messages below were generated by the user/i
const isNoise = (t: string): boolean => {
  const s = t.trimStart()
  return NOISE_TAG.test(s) || NOISE_CAVEAT.test(s)
}

/** A real, typed user prompt → record; tool-results / meta / sidechain / injected
 * harness messages → null. */
export function parseUserPrompt(line: string): PromptRec | null {
  const s = line.trim()
  if (!s || s[0] !== '{') return null
  let o: RawLine
  try {
    o = JSON.parse(s) as RawLine
  } catch {
    return null
  }
  if (o.type !== 'user' || o.isSidechain || o.isMeta || o.isCompactSummary || o.isVisibleInTranscriptOnly) {
    return null
  }
  const content = o.message?.content
  let text = ''
  if (typeof content === 'string') {
    if (isNoise(content)) return null
    text = content
  } else if (Array.isArray(content)) {
    if (content.some((b) => b && b.type === 'tool_result')) return null // tool output, not a prompt
    // Keep only real text blocks — drop any injected noise blocks (a reminder is
    // often appended alongside the real message; strip it, keep the message).
    text = content
      .filter((b) => b && b.type === 'text' && typeof b.text === 'string')
      .map((b) => b.text as string)
      .filter((t) => !isNoise(t))
      .join('\n')
  } else {
    return null
  }
  text = text.trim()
  if (!text || isNoise(text)) return null
  const parsed = Date.parse(o.timestamp ?? '')
  return { sessionId: str(o.sessionId), cwd: str(o.cwd), ts: Number.isFinite(parsed) ? parsed : 0, text }
}

const PREVIEW_MAX = 100

/** Build the indexed prompt list for one session, deduping consecutive repeats. */
export function buildHistory(sessionId: string, cwd: string, recs: PromptRec[]): SessionHistory {
  const prompts: SessionHistory['prompts'] = []
  let prev = ''
  for (const r of recs) {
    if (r.text === prev) continue // compaction replays the same prompt — skip dupes
    prev = r.text
    const firstLine = r.text.split('\n').find((l) => l.trim()) ?? r.text
    prompts.push({
      index: prompts.length,
      ts: r.ts,
      text: r.text,
      preview: firstLine.trim().slice(0, PREVIEW_MAX)
    })
  }
  return { sessionId, cwd, prompts }
}
