import { describe, it, expect } from 'vitest'
import { parseConversation, toolSummary, sliceCompleteLines, parseTailSlice } from '../../src/main/services/readingParse'

const rec = (o: unknown): string => JSON.stringify(o)

describe('toolSummary', () => {
  it('summarizes file + bash + agent tools, falls back to the name', () => {
    expect(toolSummary('Edit', { file_path: '/a/b/foo.ts' })).toBe('foo.ts')
    expect(toolSummary('Write', { file_path: 'x/README.md' })).toBe('README.md')
    expect(toolSummary('Bash', { command: 'npm run build' })).toBe('npm run build')
    expect(toolSummary('Agent', { description: 'explore repo' })).toBe('explore repo')
    expect(toolSummary('Glob', {})).toBe('Glob')
    expect(toolSummary('Read', { file_path: 'a/b/c.log' })).toBe('c.log')
    expect(toolSummary('NotebookEdit', { file_path: 'nb.ipynb' })).toBe('nb.ipynb')
  })
  it('truncates a long bash command', () => {
    const long = 'echo ' + 'x'.repeat(200)
    expect(toolSummary('Bash', { command: long }).length).toBeLessThanOrEqual(80)
  })
})

describe('parseConversation', () => {
  it('extracts user + assistant text messages in order', () => {
    const out = parseConversation([
      rec({ type: 'user', uuid: 'u1', timestamp: '2026-01-01T00:00:00Z', message: { content: 'hello' } }),
      rec({ type: 'assistant', uuid: 'a1', timestamp: '2026-01-01T00:00:01Z', message: { content: [{ type: 'text', text: 'hi there' }] } })
    ])
    expect(out.map((m) => [m.role, m.text])).toEqual([
      ['user', 'hello'],
      ['assistant', 'hi there']
    ])
  })

  it('turns tool_use into a tool row and pairs tool_result to set ok', () => {
    const out = parseConversation([
      rec({ type: 'assistant', uuid: 'a1', message: { content: [{ type: 'tool_use', id: 't1', name: 'Edit', input: { file_path: 'foo.ts' } }] } }),
      rec({ type: 'user', uuid: 'u2', message: { content: [{ type: 'tool_result', tool_use_id: 't1', is_error: false, content: 'ok' }] } })
    ])
    expect(out).toHaveLength(1)
    expect(out[0].role).toBe('tool')
    expect(out[0].tool).toEqual({ name: 'Edit', summary: 'foo.ts', ok: true })
  })

  it('marks a failed tool_result', () => {
    const out = parseConversation([
      rec({ type: 'assistant', uuid: 'a1', message: { content: [{ type: 'tool_use', id: 't1', name: 'Bash', input: { command: 'false' } }] } }),
      rec({ type: 'user', uuid: 'u2', message: { content: [{ type: 'tool_result', tool_use_id: 't1', is_error: true, content: 'boom' }] } })
    ])
    expect(out[0].tool?.ok).toBe(false)
  })

  it('drops harness noise and non-user/meta records', () => {
    const out = parseConversation([
      rec({ type: 'user', uuid: 'n1', message: { content: '<system-reminder>hidden</system-reminder>' } }),
      rec({ type: 'user', uuid: 'm1', isMeta: true, message: { content: 'meta' } }),
      rec({ type: 'user', uuid: 's1', isSidechain: true, message: { content: 'side' } }),
      rec({ type: 'user', uuid: 'c1', message: { content: 'Caveat: The messages below were generated by the user\nblah' } }),
      rec({ type: 'user', uuid: 'u1', message: { content: 'real question' } })
    ])
    expect(out.map((m) => m.text)).toEqual(['real question'])
  })

  it('collapses consecutive duplicate user prompts (compaction replay)', () => {
    const out = parseConversation([
      rec({ type: 'user', uuid: 'u1', message: { content: 'same' } }),
      rec({ type: 'user', uuid: 'u2', message: { content: 'same' } })
    ])
    expect(out).toHaveLength(1)
  })

  it('keeps a duplicate user prompt when an assistant turn separates them', () => {
    const out = parseConversation([
      rec({ type: 'user', uuid: 'u1', message: { content: 'same' } }),
      rec({ type: 'assistant', uuid: 'a1', message: { content: [{ type: 'text', text: 'reply' }] } }),
      rec({ type: 'user', uuid: 'u2', message: { content: 'same' } })
    ])
    expect(out.filter((m) => m.role === 'user')).toHaveLength(2)
  })

  it('ignores blank lines and non-JSON', () => {
    expect(parseConversation(['', '   ', 'not json'])).toEqual([])
  })
})

describe('sliceCompleteLines', () => {
  it('returns whole lines and the bytes they consumed', () => {
    const r = sliceCompleteLines('a\nb\n')
    expect(r.lines).toEqual(['a', 'b'])
    expect(r.consumed).toBe(4)
  })

  it('leaves a trailing partial line unconsumed', () => {
    const r = sliceCompleteLines('a\nb\npart')
    expect(r.lines).toEqual(['a', 'b'])
    expect(r.consumed).toBe(4) // 'a\nb\n' only — 'part' waits for the rest
  })

  it('consumes nothing when there is no complete line yet', () => {
    expect(sliceCompleteLines('partial')).toEqual({ lines: [], consumed: 0 })
  })

  it('counts multi-byte characters in bytes, not characters', () => {
    const r = sliceCompleteLines('é\n')
    expect(r.lines).toEqual(['é'])
    expect(r.consumed).toBe(3) // 2-byte é + newline
  })
})

describe('parseTailSlice', () => {
  it('start=0, text ends with \\n: end equals the byte length of the text, all lines returned', () => {
    const text = 'a\nb\n'
    const r = parseTailSlice(text, 0)
    expect(r.lines).toEqual(['a', 'b'])
    expect(r.end).toBe(Buffer.byteLength(text, 'utf8'))
  })

  it('start=0, text does NOT end with \\n: the trailing partial line is dropped and end is short of the text length (regression: no fabricated byte)', () => {
    const text = 'a\nb\npart'
    const r = parseTailSlice(text, 0)
    expect(r.lines).toEqual(['a', 'b'])
    expect(r.lines).not.toContain('part')
    expect(r.end).toBeLessThan(Buffer.byteLength(text, 'utf8'))
    expect(r.end).toBe(4)
  })

  it('start>0 with a dropped fragment: end accounts for the fragment bytes too (regression: offset must include the dropped prefix)', () => {
    // Mirrors the reviewer-reported bug: start=20, a 13-byte dropped fragment,
    // and 16 bytes of complete lines after it — true end offset is 49, not 36
    // (36 = start + consumed-of-the-already-trimmed-text, the old broken formula).
    const fragment = 'PARTIAL_TAIL\n' // 13 bytes
    expect(Buffer.byteLength(fragment, 'utf8')).toBe(13)
    const text = fragment + 'abcdefg\nhijklmn\n' // 16 more bytes of complete lines
    const r = parseTailSlice(text, 20)
    expect(r.lines).toEqual(['abcdefg', 'hijklmn'])
    expect(r.end).toBe(49)
  })

  it('counts multi-byte characters in bytes, not characters, in both the dropped fragment and the body', () => {
    const text = 'é\nü\n' // dropped fragment 'é\n' = 3 bytes, body 'ü\n' = 3 bytes
    const r = parseTailSlice(text, 5)
    expect(r.lines).toEqual(['ü'])
    expect(r.end).toBe(5 + 3 + 3)
  })
})
