import { describe, it, expect } from 'vitest'
import { parseUserPrompt, buildHistory } from '../../src/main/services/sessionHistoryParse'

const userPrompt = (text: string, opts: Record<string, unknown> = {}): string =>
  JSON.stringify({
    type: 'user',
    isSidechain: false,
    sessionId: 'sess-1',
    cwd: '/Users/me/proj',
    timestamp: '2026-06-23T10:00:00.000Z',
    promptId: 'p1',
    message: { role: 'user', content: [{ type: 'text', text }] },
    ...opts
  })

describe('parseUserPrompt', () => {
  it('parses a real typed prompt', () => {
    const r = parseUserPrompt(userPrompt('fix the bug'))
    expect(r).toMatchObject({ text: 'fix the bug', cwd: '/Users/me/proj', sessionId: 'sess-1' })
  })

  it('accepts a plain string content', () => {
    const line = JSON.stringify({
      type: 'user',
      sessionId: 's',
      cwd: '/p',
      timestamp: '2026-06-23T10:00:00.000Z',
      message: { role: 'user', content: 'hello' }
    })
    expect(parseUserPrompt(line)?.text).toBe('hello')
  })

  it('ignores tool_result user messages (not real prompts)', () => {
    const line = JSON.stringify({
      type: 'user',
      message: { content: [{ type: 'tool_result', tool_use_id: 'x', content: [{ type: 'text', text: 'out' }] }] }
    })
    expect(parseUserPrompt(line)).toBeNull()
  })

  it('ignores sidechain, meta, assistant, and empty entries', () => {
    expect(parseUserPrompt(userPrompt('x', { isSidechain: true }))).toBeNull()
    expect(parseUserPrompt(userPrompt('x', { isMeta: true }))).toBeNull()
    expect(parseUserPrompt(JSON.stringify({ type: 'assistant', message: { content: [] } }))).toBeNull()
    expect(parseUserPrompt(userPrompt('   '))).toBeNull()
    expect(parseUserPrompt('not json')).toBeNull()
  })

  it('ignores harness-injected messages that arrive as type:"user" (not real prompts)', () => {
    expect(parseUserPrompt(userPrompt('<task-notification>\n<task-id>abc</task-id>\n</task-notification>'))).toBeNull()
    expect(parseUserPrompt(userPrompt('<command-name>/compact</command-name>'))).toBeNull()
    expect(parseUserPrompt(userPrompt('<command-message>compact</command-message>'))).toBeNull()
    expect(parseUserPrompt(userPrompt('<local-command-stdout>output here</local-command-stdout>'))).toBeNull()
    expect(parseUserPrompt(userPrompt('<system-reminder>be careful</system-reminder>'))).toBeNull()
    expect(
      parseUserPrompt(userPrompt('Caveat: The messages below were generated by the user while running...'))
    ).toBeNull()
    // string-form content too
    const strForm = JSON.stringify({
      type: 'user',
      sessionId: 's',
      cwd: '/p',
      message: { role: 'user', content: '<task-notification>x</task-notification>' }
    })
    expect(parseUserPrompt(strForm)).toBeNull()
  })

  it('keeps the real message when a reminder block is appended alongside it', () => {
    const line = JSON.stringify({
      type: 'user',
      sessionId: 's',
      cwd: '/p',
      timestamp: '2026-06-23T10:00:00.000Z',
      message: {
        role: 'user',
        content: [
          { type: 'text', text: '<system-reminder>ignore me</system-reminder>' },
          { type: 'text', text: 'the actual prompt' }
        ]
      }
    })
    expect(parseUserPrompt(line)?.text).toBe('the actual prompt')
  })

  it('does not filter a normal prompt that merely contains an angle bracket', () => {
    expect(parseUserPrompt(userPrompt('use a <div> here'))?.text).toBe('use a <div> here')
    expect(parseUserPrompt(userPrompt('[Image #1] fix this'))?.text).toBe('[Image #1] fix this')
  })
})

describe('buildHistory', () => {
  const rec = (text: string, ts = 1) => ({ sessionId: 's', cwd: '/p', ts, text })

  it('indexes prompts and derives a single-line preview', () => {
    const h = buildHistory('s', '/p', [rec('first line\nmore'), rec('second')])
    expect(h.prompts.map((p) => p.index)).toEqual([0, 1])
    expect(h.prompts[0].preview).toBe('first line')
    expect(h.prompts[0].text).toBe('first line\nmore')
  })

  it('dedupes consecutive identical prompts (compaction replays)', () => {
    const h = buildHistory('s', '/p', [rec('same'), rec('same'), rec('other')])
    expect(h.prompts.map((p) => p.text)).toEqual(['same', 'other'])
  })

  it('truncates a very long preview', () => {
    const h = buildHistory('s', '/p', [rec('y'.repeat(300))])
    expect(h.prompts[0].preview.length).toBeLessThanOrEqual(100)
  })
})
